name: Release

on:
  push:
    tags:
      - "v*-build.*"

permissions: {}

jobs:
  release:
    permissions:
      actions: read
      contents: read
      id-token: write
      attestations: write
    uses: ohida/codex-echo/.github/workflows/release-build.yml@34ca34ad87b9241fe2c71c52e81445b7093ae71b
